name: frp-server

services:
    frps:
        build: ./frps
        restart: always
        network_mode: host
        environment:
            - TZ=${TIMEZONE:-Asia/Shanghai}
        volumes:
            - ${DATA_DIR}/frps.toml:/etc/frp/frps.toml
