name: docker-registry

services:
    registry:
        image: registry:2
        restart: always
        user: ${CS_UID:-1000}:${CS_GID:-1000}
        ports:
            - 5000:5000
        volumes:
            - ${DATA_DIR}/registry:/var/lib/registry
        environment:
            REGISTRY_STORAGE_DELETE_ENABLED: "true"
