name: minecraft-blessing-skin

services:
    app:
        build:
            context: ./blessing-skin
            args:
                - UID=${PUID:-1000}
                - GID=${PGID:-1000}
        restart: always
        user: ${PUID:-1000}:${PGID:-1000}
        ports:
            - "25580:80"
        volumes:
            - ${DATA_DIR:-.}/plugins:/app/plugins
            - ${DATA_DIR:-.}/skin:/app/skin
            - ${DATA_DIR:-.}/storage:/app/storage
            - ${DATA_DIR:-.}/.env:/app/.env
            - ${DATA_DIR:-.}:/data
            - /etc/localtime:/etc/localtime:ro

    redis:
        image: redis:alpine
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
