name: minecraft-blessing-skin

services:
    app:
        build: ./blessing-skin
        restart: always
        environment:
            TZ: "${TIMEZONE:-Asia/Shanghai}"
        ports:
            - "25580:80"
        volumes:
            - ${DATA_DIR:-./data}/plugins:/app/plugins
            - ${DATA_DIR:-./data}/skin:/app/skin
            - ${DATA_DIR:-./data}/storage:/app/storage
            - ${DATA_DIR:-./data}/.env:/app/.env
            - ${DATA_DIR:-./data}:/data
        command: /bin/command.sh

    redis:
        image: redis:alpine
        restart: always
        environment:
            - TZ=${TIMEZONE:-Asia/Shanghai}
