name: frp-server

services:
    frps:
        build: ./frps
        restart: always
        network_mode: host
        volumes:
            - /home/user/containerized-service-data/frp-server/frps.toml:/etc/frp/frps.toml
